---
- name: 開発環境構築
  hosts: all
  become: yes
  remote_user: vagrant
  
  tasks:
    - name: setup node.js
      shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    - name: install node.js
      apt: name=nodejs
